export const PINOS = {
  'Alvarães':          { pin: '2306',  nivel: 'maximo' },
  'Pr. Júnior':        { pin: '5050',  nivel: 'maximo' },
  'Alyson':            { pin: '2121',  nivel: 'maximo' },
  'Pra. Stephanie':    { pin: '4780',  nivel: 'alto'   },
  'Caetano':           { pin: '0404',  nivel: 'alto'   },
  'Jhony':             { pin: '7780',  nivel: 'medio'  },
  'Gustavo Massay':    { pin: '1121',  nivel: 'medio'  },
  'Walterley':         { pin: '3123',  nivel: 'medio'  },
  'Francisco':         { pin: '6689',  nivel: 'medio'  },
  'Danilo':            { pin: '6090',  nivel: 'basico' },
  'Eliel':             { pin: '1778',  nivel: 'basico' },
  'Edson':             { pin: '3321',  nivel: 'basico' },
  'Paula':             { pin: '9089',  nivel: 'basico' },
  'Clara Cunha':       { pin: '47823', nivel: 'staff'  },
  'Daniel':            { pin: '19654', nivel: 'staff'  },
  'Edson Jr.':         { pin: '82391', nivel: 'staff'  },
  'Emanuel':           { pin: '35617', nivel: 'staff'  },
  'Gabriel Gomes':     { pin: '64028', nivel: 'staff'  },
  'Gustavo Borges':    { pin: '91473', nivel: 'staff'  },
  'Hadstton Capell':   { pin: '28509', nivel: 'staff'  },
  'Hellen Borges':     { pin: '73142', nivel: 'staff'  },
  'Hugo Lacroix':      { pin: '50836', nivel: 'staff'  },
  'Isabely Matos':     { pin: '16294', nivel: 'staff'  },
  'Jerônimo':          { pin: '84751', nivel: 'staff'  },
  'Joel Marcos':       { pin: '39208', nivel: 'staff'  },
  'Joyce':             { pin: '62547', nivel: 'staff'  },
  'Juliana':           { pin: '15983', nivel: 'staff'  },
  'Letícia':           { pin: '70364', nivel: 'staff'  },
  'Linda':             { pin: '43891', nivel: 'staff'  },
  'Lívia Andréa':      { pin: '27536', nivel: 'staff'  },
  'Lorena':            { pin: '98142', nivel: 'staff'  },
  'Ludmyla':           { pin: '54067', nivel: 'staff'  },
  'Maria Clara':       { pin: '31759', nivel: 'staff'  },
  'Maria Júlia':       { pin: '86423', nivel: 'staff'  },
  'Mariana Gabrielle': { pin: '49178', nivel: 'staff'  },
  'Matheus Almeida':   { pin: '63015', nivel: 'staff'  },
  'Maurício':          { pin: '72894', nivel: 'staff'  },
  'Nicoly':            { pin: '18347', nivel: 'staff'  },
  'Rafael Chaves':     { pin: '95621', nivel: 'staff'  },
  'Rennan':            { pin: '40783', nivel: 'staff'  },
  'Ryan Guedes':       { pin: '57290', nivel: 'staff'  },
  'Samuel Lopes':      { pin: '23416', nivel: 'staff'  },
  'Sthefany':          { pin: '68934', nivel: 'staff'  },
  'Taiwa':             { pin: '14567', nivel: 'staff'  },
  'Victória':          { pin: '80259', nivel: 'staff'  },
}

export const NOMES = Object.keys(PINOS).sort((a, b) => a.localeCompare(b, 'pt-BR'))
